name: Test PR Build
on:
  pull_request:
    types: [opened, synchronize, labeled, unlabeled]
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  check_labels:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4 # Use this action to checkout your repository
        with:
          fetch-depth: 0 # Fetch all history for all branches and tags

      - name: List PR labels
        run: |
          echo "Pull request labels:"
          echo '${{ toJSON(github.event.pull_request.labels.*.name) }}' | jq -r '.[]'
          
      - name: Check CHANGELOG
        run: |
          if echo '${{ toJSON(github.event.pull_request.labels.*.name) }}' | jq -r '.[]' | grep -q "Skip Changelog"; then
            echo "Skip Changelog label found - check passed"
            exit 0
          fi
          
          git fetch origin ${{ github.base_ref }}
          if git diff --name-only origin/${{ github.base_ref }}...HEAD | grep -q "CHANGELOG"; then
            echo "CHANGELOG entry found - check passed"
            exit 0
          fi
          
          echo "It looks like you didn't add an entry to CHANGELOG.md. If this change affects the SDK behavior, please update CHANGELOG.md and link this PR in your entry. If this PR does not need a CHANGELOG entry, you can add the 'Skip Changelog' label to this PR."
          exit 1
