name: Test PR Build
on:
  pull_request:
    types: [opened, synchronize, labeled, unlabeled]
    branches:
      - main

jobs:
  changelog-check:
    runs-on: ubuntu-latest
    steps:
      - name: Check for skip conditions
        run: |
          if [[ "${{ github.event.pull_request.user.login }}" == "aws-application-signals-bot" ]]; then
            echo "Skipping: PR from bot"
            exit 0
          fi
          
          # Check for Skip Changelog label
          echo "Labels on PR:"
          gh pr view ${{ github.event.pull_request.number }} --json labels --jq '.labels[].name'
          
          if gh pr view ${{ github.event.pull_request.number }} --json labels --jq '.labels[].name' | grep -q "Skip Changelog"; then
            echo "Skipping: Skip Changelog label found"
            exit 0
          fi
          
          echo "Proceeding with CHANGELOG check"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - name: Check CHANGELOG
        run: |
          if gh pr view ${{ github.event.pull_request.number }} --json labels --jq '.labels[].name' | grep -q "Skip Changelog"; then
            echo "Skip Changelog label found"
            exit 0
          fi
          
          if git diff --name-only origin/${{ github.base_ref }}...HEAD | grep -q "CHANGELOG"; then
            echo "CHANGELOG entry found"
            exit 0
          fi
          
          echo "::error::No CHANGELOG entry found. Add a CHANGELOG entry or apply the 'Skip Changelog' label."
          exit 1
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  test-job:
    runs-on: ubuntu-latest
    needs: changelog-check
    steps:
      - uses: actions/checkout@v4
      - name: Dummy test
        run: echo "All checks passed!"
