name: Test PR Build
on:
  pull_request:
    types: [opened, synchronize, labeled, unlabeled]
    branches:
      - main

jobs:
  changelog-check:
    runs-on: ubuntu-latest
    steps:
      - name: Debug labels
        run: |
          echo "PR author: ${{ github.event.pull_request.user.login }}"
          echo "Labels: ${{ toJson(github.event.pull_request.labels.*.name) }}"
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
        if: github.event.pull_request.user.login != 'aws-application-signals-bot' && !contains(github.event.pull_request.labels.*.name, 'Skip Changelog')
      - name: Check CHANGELOG
        if: github.event.pull_request.user.login != 'aws-application-signals-bot' && !contains(github.event.pull_request.labels.*.name, 'Skip Changelog')
        run: |
          if git diff --name-only origin/${{ github.base_ref }}...HEAD | grep -q "CHANGELOG"; then
            echo "CHANGELOG entry found"
            exit 0
          fi
          echo "::error::No CHANGELOG entry found. Add a CHANGELOG entry or apply the 'Skip Changelog' label."
          exit 1

  test-job:
    runs-on: ubuntu-latest
    needs: changelog-check
    steps:
      - uses: actions/checkout@v4
      - name: Dummy test
        run: echo "All checks passed!"
