name: Test CHANGELOG Update

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version number (e.g., 1.0.1)'
        required: true
        default: '1.1.0'
      is_patch:
        description: 'Is this a patch? (true or false)'
        required: true
        default: 'false'
      scenario:
        description: 'Test scenario'
        required: true
        type: choice
        options:
          - 'normal-unreleased'
          - 'empty-unreleased'
          - 'patch-existing'
          - 'no-unreleased-section'

jobs:
  test-changelog:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup test scenario
        run: |
          VERSION="${{ github.event.inputs.version }}"
          SCENARIO="${{ github.event.inputs.scenario }}"
          
          case $SCENARIO in
            "normal-unreleased")
              cat > CHANGELOG.md << 'EOF'
          # Changelog
          
          ## Unreleased
          
          ### Added
          - New feature X
          - Support for Y
          
          ### Fixed
          - Bug fix A
          
          ## 1.0.0 - 2024-08-01
          
          ### Added
          - Initial release
          EOF
              ;;
              
            "empty-unreleased")
              cat > CHANGELOG.md << 'EOF'
          # Changelog
          
          ## Unreleased
          
          ## 1.0.0 - 2024-08-01
          
          ### Added
          - Initial release
          EOF
              ;;
              
            "patch-existing")
              cat > CHANGELOG.md << 'EOF'
          # Changelog
          
          ## Unreleased
          
          ## 1.0.1 - 2025-09-08
          
          ### Fixed
          - Critical security fix
          
          ## 1.0.0 - 2024-08-01
          
          ### Added
          - Initial release
          EOF
              ;;
              
            "no-unreleased-section")
              cat > CHANGELOG.md << 'EOF'
          # Changelog
          
          ## 1.0.0 - 2024-08-01
          
          ### Added
          - Initial release
          EOF
              ;;
          esac
          
          echo "=== BEFORE ==="
          cat CHANGELOG.md
          
      - name: Test CHANGELOG update (non-patch)
        if: github.event.inputs.is_patch != 'true'
        run: |
          VERSION="${{ github.event.inputs.version }}"
          
          # Replace "## Unreleased" with "## ${VERSION} - $(date +%Y-%m-%d)"
          sed -i "s/## Unreleased/## ${VERSION} - $(date +%Y-%m-%d)/" CHANGELOG.md
          
          echo "=== AFTER (non-patch) ==="
          cat CHANGELOG.md
          
      - name: Test CHANGELOG update (patch - should skip)
        if: github.event.inputs.is_patch == 'true'
        run: |
          echo "=== PATCH RELEASE - NO CHANGES ==="
          cat CHANGELOG.md
