name: Test CHANGELOG Update

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version number (e.g., 1.0.1)'
        required: true
        default: '1.1.0'

jobs:
  test-changelog:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Show original CHANGELOG
        run: |
          echo "=== ORIGINAL CHANGELOG ==="
          cat CHANGELOG.md
          
      - name: Show release branch CHANGELOG
        run: |
          VERSION="${{ github.event.inputs.version }}"
          
          # Copy original for release branch simulation
          cp CHANGELOG.md CHANGELOG_release.md
          
          # Replace "## Unreleased" with "## ${VERSION} - $(date +%Y-%m-%d)"
          sed -i "s/## Unreleased/## ${VERSION} - $(date +%Y-%m-%d)/" CHANGELOG_release.md
          
          echo "=== RELEASE BRANCH CHANGELOG ==="
          cat CHANGELOG_release.md
          
      - name: Show main branch CHANGELOG
        run: |
          VERSION="${{ github.event.inputs.version }}"
          
          # Copy original for main branch simulation
          cp CHANGELOG.md CHANGELOG_main.md
          
          # Keep Unreleased + add release entry
          sed -i "s/## Unreleased/## Unreleased\n\n## ${VERSION} - $(date +%Y-%m-%d)/" CHANGELOG_main.md
          
          echo "=== MAIN BRANCH CHANGELOG ==="
          cat CHANGELOG_main.md
