name: Test Release Notes

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Test version (e.g., 1.0.0)'
        required: true
        type: string

jobs:
  test-notes:
    runs-on: ubuntu-latest
    steps:
      - name: Create release notes template
        run: |
          # Create release notes template
          cat > release_notes.md << 'EOF'
          This release contains the following upstream components:

          - `@opentelemetry/api` - <dependency version number>
          - `@opentelemetry/auto-configuration-propagators` - <dependency version number>
          - `@opentelemetry/auto-instrumentations-node` - <dependency version number>
          - `@opentelemetry/core` - <dependency version number>
          - `@opentelemetry/exporter-metrics-otlp-grpc` - <dependency version number>
          - `@opentelemetry/exporter-metrics-otlp-http` - <dependency version number>
          - `@opentelemetry/exporter-trace-otlp-proto` - <dependency version number>
          - `@opentelemetry/exporter-zipkin` - <dependency version number>
          - `@opentelemetry/id-generator-aws-xray` - <dependency version number>
          - `@opentelemetry/instrumentation` - <dependency version number>
          - `@opentelemetry/instrumentation-aws-sdk` - <dependency version number>
          - `@opentelemetry/propagator-aws-xray` - <dependency version number>
          - `@opentelemetry/resource-detector-aws` - <dependency version number>
          - `@opentelemetry/resources` - <dependency version number>
          - `@opentelemetry/sdk-metrics` - <dependency version number>
          - `@opentelemetry/sdk-node` - <dependency version number>
          - `@opentelemetry/sdk-trace-base` - <dependency version number>
          - `@opentelemetry/semantic-conventions` - <dependency version number>
          - `<ANY NEW DEPENDENCIES>` - <new dependency version number>

          This release also publishes to public ECR and NPM.
          * See ADOT node auto-instrumentation Docker image v${{ github.event.inputs.version }} in our public ECR repository:
          https://gallery.ecr.aws/aws-observability/adot-autoinstrumentation-node
          * See version ${{ github.event.inputs.version }} in our NPM repository:
          https://www.npmjs.com/package/@aws/aws-distro-opentelemetry-node-autoinstrumentation
          EOF

      - name: Display release notes content
        run: |
          echo "=== Release Notes Content ==="
          cat release_notes.md
          echo ""
          echo "=== File Info ==="
          ls -la release_notes.md
          wc -l release_notes.md
